#
# version.cmake : version du projet
#

set (MACHINE_TYPES_MAJOR_VERSION "2")
set (MACHINE_TYPES_MINOR_VERSION "0")
set (MACHINE_TYPES_RELEASE_VERSION "0")
set (MACHINE_TYPES_VERSION ${MACHINE_TYPES_MAJOR_VERSION}.${MACHINE_TYPES_MINOR_VERSION}.${MACHINE_TYPES_RELEASE_VERSION})


